### ISSUE TITLE
Messages sent by appMaker to start a conversation with a appUser don't display until refreshing the page

### ISSUE THREAD

**Issue by sauronnikko** [smooch/smooch-web#626]
I opened this [issue](https://github.com/smooch/smooch-core-js/issues/95) on **smooch-core-js** repo. I was told that this bug belonged in this repo instead.

**Comment by lemieux** [comment]
Hey @sauronnikko, as mentionned by @Go-Fred in the other issue, this use case isn't supported. Faye doesn't connect to the server until the user starts messaging (in case the conversation isn't already going before loading) or if the conversation is already existing. This is an intended behavior to avoid creating connections for every user since it creates a lot of unnecessary load on the platform. You could force-start the conversation by sending a message on behalf of your user using `Smooch.sendMessage()` so the conversation starts.

Also, since version 4.0.0, `getCore` has been deprecated and removed from the API. 

As for proactively reaching the users, we have that on roadmap, but no timeline or definitive plan yet.

**Comment by nikkwong** [comment]
I'm trying to do this exactly, but `Smooch.sendMessage()` throws an uncaught promise:

```
VM120108:1 Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at c (frame.4.3.4.min.js:16)
    at t.value (frame.4.3.4.min.js:26)
    at t.value (frame.4.3.4.min.js:26)
```

**Comment by mspensieri** [comment]
@nikkwong you can use the [startConversation](https://github.com/smooch/smooch-web#startconversation) method as of [v4.4.0](https://github.com/smooch/smooch-web/releases/tag/4.4.0).

See our [business initiated conversations](https://docs.smooch.io/guide/business-initiated-conversations/) guide for more information
