### ISSUE TITLE
How to change iframe default icon color

### ISSUE THREAD

**Issue by gazpachu** [smooch/smooch-web#647]
At the moment, the SVG `<path>` has a `fill:#55555d` attribute. I've tried targeting the element but it doesn't seem to be working:

```
iframe #messenger-button {
  .default-icon {
    fill: $black;
  }
}
```

![screen shot 2017-11-07 at 10 32 41](https://user-images.githubusercontent.com/1721288/32486474-061ea2a8-c3a7-11e7-9c5e-c83c68761d67.png)

**Comment by mspensieri** [comment]
The color of the icon will automatically adjust to light or dark depending on the color you choose as your Brand Color in the Smooch dashboard. 

Your CSS override doesn't work because styles in the iframe are not affected by stylesheets in the host page. Full customization of the icon color isn't currently supported, but you can upload your own image on the Smooch dashboard in the Web Messenger settings page to customize the appearance of that badge.

**Comment by gazpachu** [comment]
@mspensieri I understand is not currently supported but I would like it to be considered for future releases, as the chat icon is quite relevant (it appears on every page), so its style should be customisable. Thanks

**Comment by mspensieri** [comment]
Thanks, I'll bring your feedback to the team. Just to be clear though, you are still able to fully customize the style of the badge by uploading your own image

**Comment by gazpachu** [comment]
Yes but it doesn't accept SVG file uploads, which is what we use in all our projects :/
