### ISSUE TITLE
Webview Connection Refused

### ISSUE THREAD

**Issue by SherifBashar** [smooch/smooch-web#673]
Hi,

is it normal for the Webview to refuse connection when the url starts with **www.** ?

for example the below link will refuse to connect

https://www.google.com/maps/place/30%C2%B002'44.6%22N+31%C2%B020'42.4%22E/@30.0547034,31.3315684,19.81z/data=!4m5!3m4!1s0x0:0x0!8m2!3d30.0457326!4d31.3450986

but this https://smooch.io will connect successfully.

Please help.

**Comment by mspensieri** [comment]
@SherifBashar the issue is that Google is returning [`X-Frame-Options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) `sameorigin` to prevent the page from loading in an `iframe`, it's not related to the format of the URL. The browser is refusing to render the page because of the presence of that response header - Google has specifically configured their page with this header to prevent the page from being embedded on someone else's website. To use this URL, you would need to send a `link` type action instead, which will open the link in a new tab.

**Comment by SherifBashar** [comment]
@mspensieri I read about the frame killer thing .. Yeah you are right it's not an issue in Smooch Webview .. thanks for your prompt reply.
